"""Local callback wrapper for ceil-dlp.

This file is auto-generated by 'ceil-dlp install'. It provides a local import
path for LiteLLM to use ceil-dlp as a callback.
"""

import os
import sys
from pathlib import Path

# Add this directory to sys.path so LiteLLM can import this module
# regardless of where it's run from
_config_dir = Path(__file__).parent
if str(_config_dir) not in sys.path:
    sys.path.insert(0, str(_config_dir))

# Import from the installed ceil-dlp package
# This import is needed for LiteLLM to discover the handler instance
from ceil_dlp.ceil_dlp_callback import (  # noqa: E402
    proxy_handler_instance,  # noqa: F401  # type: ignore[unused-import]
)

# Set CEIL_DLP_CONFIG_PATH to use ceil-dlp.yaml in the same directory as this file
_config_file = _config_dir / "ceil-dlp.yaml"

if _config_file.exists():
    os.environ["CEIL_DLP_CONFIG_PATH"] = str(_config_file)
